### ISSUE TITLE
Meteor Todo App tests hanging with nightmare

### ISSUE THREAD

**Issue by keyscores** [DispatchMe/meteor-mocha#11]
Seems to work on another blank app with do nothing tests. But after using Meteor Todos app as a reference, some issues come up.

Server tests work fine, as expected.

Client app tests with --full-app worked once. Then on a second and subsequent runs it started hanging with no error after printing "client tests running". It's failing silently with no errors in 'debug'.

This command:
`TEST_BROWSER_DRIVER=nightmare DEBUG=* meteor test --once  --driver-package dispatch:mocha`

**Comment by keyscores** [comment]
This is odd. Using Nightmare in a new blank meteor project works. Though adding and importing Nightmare to the Todos app (and other apps) causes this failure:

W20170217-14:22:16.891(-5)? (STDERR) Error: Cannot find module './actions'
W20170217-14:22:16.891(-5)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20170217-14:22:16.892(-5)? (STDERR)     at meteorInstall.node_modules.nightmare.lib.nightmare.js.options.queue.proc.stdout.pipe.on.proc.stderr.pipe.on.proc.on.instance.proc.on.instance (packages/modules.js:413:15)
W20170217-14:22:16.892(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170217-14:22:16.893(-5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170217-14:22:16.893(-5)? (STDERR)     at meteorInstall.server.testnightmare.js (server/testnightmare.js:1:17)
W20170217-14:22:16.893(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170217-14:22:16.894(-5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170217-14:22:16.895(-5)? (STDERR)     at /Users/LUCAS/Downloads/todos-master/.meteor/local/build/programs/server/app/app.js:1142:1
W20170217-14:22:16.896(-5)? (STDERR)     at /Users/LUCAS/Downloads/todos-master/.meteor/local/build/programs/server/boot.js:295:34
W20170217-14:22:16.896(-5)? (STDERR)     at Array.forEach (native)

**Comment by keyscores** [comment]
Added here https://github.com/meteor/todos/pull/219

**Comment by keyscores** [comment]
I'm not getting `Electron[2464:70132] Cannot load Interface Builder file 'NSAlertPanel'` which seems to be related to  "Too many open files" ( https://github.com/electron/electron/issues/4828 ). 

The meteor bug tracking this is:
https://github.com/meteor/meteor/issues/6952

**Comment by keyscores** [comment]
We can close, this fix worked for me: METEOR_WATCH_FORCE_POLLING=1
